name: Metrics
on:
  # Schedule Updates Every Minute
  schedule: [{cron: "* * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          #Options
          user: D7x8
          template: classic
          base: header, activity, community
          config_timezone: Pacific/Auckland
          plugin_lines: yes
          plugin_lines_delay: 30
          plugin_languages: yes
          plugin_languages_details: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_rss: yes
          plugin_rss_source: https://news.ycombinator.com/rss
          plugin_rss_limit: 4
          #plugin_chess: yes
          #plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          #plugin_chess_platform: lichess.org
